stages:
  - build

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

build:jdk8:
  image: maven:3-jdk-8-alpine
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

build:jdk9:
  image: maven:3-jdk-9-slim
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

build:jdk10:
  image: maven:3-jdk-10-slim
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

build:jdk11:
  image: maven:3-jdk-11-slim
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

build:jdk12:
  image: maven:3-jdk-12
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile
